[package]
name = "oos-lite-core"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
blake3 = { workspace = true }
crc32fast = { workspace = true }
fastcdc = { workspace = true }
sled = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }
zstd = { workspace = true }
fs2 = { workspace = true }
chacha20poly1305 = { workspace = true }
argon2 = { workspace = true }
rand_core = { workspace = true }
zeroize = { workspace = true }
notify = { workspace = true }
walkdir = { workspace = true }
glob = { workspace = true }


[dev-dependencies]
tempfile = "3.8"
tracing-subscriber = { workspace = true }
